services:
  - type: web
    name: buzzer-salapakshi
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://lanbixinfo:VfcMo7euOiX1mJ1w@interview-backend.p4usgoo.mongodb.net/interview?retryWrites=true&w=majority&appName=Interview-backend
      - key: GOOGLE_CLIENT_ID
        value: 372772514971-54vidsc825iq1rmvfu9c7gg0oto1ue7m.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: NEXTAUTH_SECRET
        value: your_nextauth_secret_here
      - key: NEXTAUTH_URL
        value: https://your-app-name.onrender.com
